### ISSUE TITLE
Add Status information to defined CRD 

### ISSUE THREAD

**Issue by wltbenade** [AbsaOSS/samlet#32]
Hi guys,

During our testing, we didn't define the ADFS secret prior to publishing the saml2aws definition, and had to check the logs of the operator to figure out what the issue was, as the operator's status on the CR's generation wasn't available on the saml2aws definition.

Would it be possible to add a Status field to the definition to reflect any operator issues relating to it, i.e. Provisioning/Error/Completed, as well as the message from the operator, i.e. From the reconciler error

{"reconcilerGroup": "samlet.absa.oss", "reconcilerKind": "Saml2Aws", "controller": "saml2aws", "name": "saml2aws-sample", "namespace": "<REDACTED>", "error": "Secret \"aws-login\" not found"}

We'll get {"error": "Secret \"aws-login\" not found"}.

Cheers!

**Comment by k0da** [comment]
@wltbenade let me check If I can implement it quickly

**Comment by divbasson2** [comment]
Any feedback on this?

**Comment by k0da** [comment]
Yes, writing tests
